# Generated by Django 2.1.7 on 2019-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190214_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publication_date',
        ),
    ]
